### ISSUE TITLE
Why PGO is better than epgsql + poolboy?

### ISSUE THREAD

**Issue by manuel-rubio** [dbi-beam/dbi_pgo#1]
@ tsloughter I'm curious about this.

**Comment by tsloughter** [comment]
You had a space in `@ tsloughter` so I never saw this until now after noticing `dbi_pgo` depending on `pgo` in hex :). Still curious?

**Comment by manuel-rubio** [comment]
@tsloughter for sure!

**Comment by tsloughter** [comment]
@manuel-rubio cool. I try to answer some of that with quick bullet points in the readme https://github.com/erleans/pgo#why

An important difference with use of poolboy for a pool is how connections are used. Like is done in most implementations of epgsql+poolboy the app https://github.com/epgsql/pgapp/ passes the query to a worker, runs the query, decodes the results and returns the results through a reply -- that means additional copying because it has to copy from the worker process back to the process that asked for the query to be run.

pgo instead checks out the connection socket and uses it int he same process as the calls to `pgo:query` were made. 

The design of the pool is pretty neat and I'd suggest checking out the low level details of the pool that can be found in this PR to Elixir's db_connection https://github.com/elixir-ecto/db_connection/pull/108 -- I stole the design from it for pgo :)

pgo also just has a simpler interface, but that also means it is lacking some control and some features, so it depends on what the user needs -- not that features couldn't be added to pgo.

pgo also uses https://github.com/tsloughter/pg_types for encoding/decoding binary postgres types. 

I hope one day epgsql, and any other active Erlang postgres client, will also use `pg_types` so we can work together on supporting all types https://github.com/epgsql/epgsql/issues/180

Currently there is a blocker for epgsql to move to pg_types, the tuple type in pg_types relies on looking up oid information from a `persistent_term` and epgsql needs to support older OTPs -- https://github.com/tsloughter/pg_types/pull/7#issuecomment-552205199

**Comment by tsloughter** [comment]
I plan to break out the connection pool to its own library. Figured that might be of use to the `dbi` project.

**Comment by manuel-rubio** [comment]
@tsloughter yes, that could be great! thanks!
